---
id: Crypt_Blowfish
name: Crypt_Blowfish
full: Blowfish encryption library
description: A library that provides blowfish encryption/decryption for PHP string data.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Crypt_Blowfish
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 1.1.4
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Support: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
    ext:
      mcrypt: '*'
      openssl: '*'
