---
id: Crypt_Blowfish
name: Crypt_Blowfish
full: Blowfish encryption library
description: A library that provides blowfish encryption/decryption for PHP string data.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Crypt_Blowfish
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
      horde/support: ^3
  dev:
    composer:
      horde/test: ^3
  optional:
    ext:
      mcrypt: '*'
      openssl: '*'
